#!/usr/bin/env bash
# Reproduce the ontology-value experiments' data and statistics on this machine, without a judge model, and compare every
# output with the committed, reviewed one. Never writes into runs/; everything goes to a temporary directory.
#   bash skills/ontology-value-repro/scripts/repro-check.sh            # from the jev-runtime-observability checkout
#   KEEP=1 ...  keeps the temporary directory;  SKIP_STATS=1 ... checks data only (about 1 minute instead of about 4)
set -uo pipefail
cd "$(dirname "$0")/../../.."
J=$PWD; W=$(cd .. && pwd); SM="$W/silex-mockup"
ARCHIVE="$SM/swm/.cache/agentdojo-repo-089ed468cf3e.tar.gz"
ARCHIVE_URL=https://codeload.github.com/ethz-spylab/agentdojo/tar.gz/089ed468cf3ed0322acc66b0211f26d9d90dbf60
ARCHIVE_SHA=d7e0ee021be27a69e7e66647979b5a5e0dd10030d38d04ce4102e18a76a228d8
T=$(mktemp -d); fails=0
ok() { echo "ok   $*"; }; bad() { echo "FAIL $*"; fails=$((fails+1)); }
trap '[ -n "${KEEP:-}" ] && echo "kept $T" || rm -rf "$T"' EXIT

# 1. tools
node -e 'const [a,b]=process.versions.node.split(".").map(Number); process.exit(a>23||(a==23&&b>=6)?0:1)' && ok "node $(node --version) (>= 23.6)" || bad "node >= 23.6 required (runs .ts directly)"
python3 -c 'import sys; sys.exit(0 if sys.version_info>=(3,10) else 1)' && ok "python $(python3 --version | cut -d' ' -f2)" || bad "python3 >= 3.10 required"
for c in shasum tar gunzip curl; do command -v $c >/dev/null && ok "$c" || bad "$c missing"; done
[ -d "$SM/.git" ] && ok "silex-mockup sibling checkout at $SM" || bad "silex-mockup must be cloned next to this repo ($SM)"
[ -d node_modules/zod ] && ok "npm dependencies" || bad "run npm ci in $J"
[ "$fails" = 0 ] || { echo "$fails prerequisite(s) missing"; exit 1; }

# 2. AgentDojo archive (whole repository at the pin; its runs/ directory holds the published agent runs)
if [ ! -f "$ARCHIVE" ]; then echo "downloading AgentDojo archive (~39 MB)"; mkdir -p "$(dirname "$ARCHIVE")"; curl -fsSL "$ARCHIVE_URL" -o "$ARCHIVE"; fi
[ "$(shasum -a 256 "$ARCHIVE" | cut -d' ' -f1)" = "$ARCHIVE_SHA" ] && ok "archive sha256 $ARCHIVE_SHA" || { bad "archive sha256 differs; delete $ARCHIVE and retry"; exit 1; }

# 3. held-out inputs, regenerated by the converter and compared with the sealed input manifests
conv() { node eval/ontology/runs-convert.ts "$@" > /dev/null; }
conv --out "$T/e5"
conv --models claude-3-7-sonnet-20250219,gemini-2.0-flash-001,gpt-4o-2024-05-13,command-r-plus --out "$T/v2"
conv --models claude-3-5-sonnet-20241022,gemini-1.5-pro-002,gpt-4o-mini-2024-07-18,command-r,meta-llama_Llama-3-70b-chat-hf --out "$T/al"
conv --models claude-3-5-sonnet-20240620,claude-3-opus-20240229,gpt-4-turbo-2024-04-09,gpt-4-0125-preview,gemini-1.5-flash-002,gemini-1.5-pro-001 --out "$T/pr" --labels-pr
conv --cohorts eval/ontology/s1/cohorts.json --out "$T/s1" --labels-pr
for f in observations.jsonl labels.jsonl; do
  want=$(python3 -c "import json;print(json.load(open('runs/onto-inputs-MANIFEST.json'))['runs/onto-e5-input/$f'])")
  [ "$(shasum -a 256 "$T/e5/$f" | cut -d' ' -f1)" = "$want" ] && ok "E1/E5 input $f" || bad "E1/E5 input $f"
done
for x in v2 al pr s1; do
  sed "s#runs/onto-$x-input#$T/$x#" "runs/onto-$x-INPUT-MANIFEST.sha256" | shasum -a 256 -c --quiet - && ok "$x inputs match runs/onto-$x-INPUT-MANIFEST.sha256" || bad "$x inputs"
done
[ -n "${SKIP_STATS:-}" ] && { echo "$fails failure(s) (statistics skipped)"; exit $((fails>0)); }

# 4. statistics, recomputed and compared byte for byte with the committed outputs (judge scores come from committed predictions)
FZ=eval/ontology/v2/frozen; SB="$SM/swm/experiments/ontology-value/pr/source-binding.json"
same() { cmp -s "$1" "$2" && ok "$3 identical to $2" || bad "$3 differs from $2"; }
for m in kev-0.8b-ft kev-0.8b; do
  gunzip -c "runs/onto-v2-$m/predictions-A0.jsonl.gz" > "$T/v2-$m.jsonl"
  node eval/ontology/v2/stats-v2.ts --input "$T/v2" --kev "$T/v2-$m.jsonl" --out "$T/stats-v2-$m.json" && same "$T/stats-v2-$m.json" "runs/onto-v2-stats/stats-$m.json" "v2 ($m)"
done
node eval/ontology/al/stats-al.ts --input "$T/al" --out "$T/stats-al.json" && same "$T/stats-al.json" runs/onto-al-stats/stats-al.json "E-AL stats"
python3 eval/ontology/al/recheck_al.py --observations "$T/al/observations.jsonl" --labels "$T/al/labels.jsonl" --snapshot $FZ/snapshot.json \
  --manifest $FZ/tool-manifest-v2.json --binding $FZ/binding-v2.json --out "$T/recheck-al.json" && same "$T/recheck-al.json" runs/onto-al-stats/recheck-al.json "E-AL recheck"
gunzip -c runs/onto-pr-judge/predictions-pr.jsonl.gz > "$T/predictions-pr.jsonl"
node eval/ontology/pr/sanitize.ts --in "$T/pr/observations.jsonl" --out "$T/pr/observations.sanitized.jsonl" > /dev/null
node eval/ontology/pr/stats-pr.ts --sanitized "$T/pr/observations.sanitized.jsonl" --labels "$T/pr/labels.jsonl" --labels-pr "$T/pr/labels-pr.jsonl" \
  --predictions "$T/predictions-pr.jsonl" --source-binding "$SB" --out "$T/stats-pr.json" && same "$T/stats-pr.json" runs/onto-pr-stats/stats-pr.json "E-PR stats"
node eval/ontology/pr/sanitize.ts --in "$T/s1/observations.jsonl" --out "$T/s1/observations.sanitized.jsonl" > /dev/null
node eval/ontology/s1/stats-s1.ts --sanitized "$T/s1/observations.sanitized.jsonl" --labels "$T/s1/labels.jsonl" --labels-pr "$T/s1/labels-pr.jsonl" \
  --out "$T/stats-s1.json" && same "$T/stats-s1.json" runs/onto-s1-stats/stats-s1.json "Stage-1 stats"
python3 eval/ontology/s1/recheck_s1.py --raw-observations "$T/s1/observations.jsonl" --labels "$T/s1/labels.jsonl" --labels-pr "$T/s1/labels-pr.jsonl" \
  --snapshot $FZ/snapshot.json --manifest $FZ/tool-manifest-v2.json --binding $FZ/binding-v2.json --out "$T/recheck-s1.json" \
  && same "$T/recheck-s1.json" runs/onto-s1-stats/recheck-s1.json "Stage-1 recheck"
node -e 'const s=require(process.argv[1]);console.log(`     Stage-1 verdict ${s.verdict}: alerts ${s.observed.prov.F} -> ${s.observed.s1.F}, precision ${s.observed.prov.precision.toFixed(3)} -> ${s.observed.s1.precision.toFixed(3)}, recall ${s.observed.prov.recall.toFixed(3)} -> ${s.observed.s1.recall.toFixed(3)}`)' "$T/stats-s1.json" 2>/dev/null
echo "$fails failure(s)"; exit $((fails>0))
